### ISSUE TITLE
Props aren't always working as expected

### ISSUE THREAD

**Issue by adampash** [missive/emoji-mart#651]
I'm using emoji-mart with React, with the following component:

```tsx
const EmojiPicker = ({
  onEmojiSelect,
}: {
  onEmojiSelect: (emojiObject: EmojiObject) => void;
}) => {
  const ref = useRef<HTMLDivElement>(null);
  const hasBeenRendered = useRef(false);

  useEffect(() => {
    if (!hasBeenRendered.current) {
      new EmojiMart.Picker({
        data,
        ref,
        theme: 'light',
        autoFocus: true,
        onEmojiSelect,
      });
      hasBeenRendered.current = true;
    }
  }, [onEmojiSelect, ref]);

  return <div ref={ref} />;
};
```

The problem I'm having is that `theme` and `autoFocus` don't seem to be working. My system default is dark, and it always renders the dark theme for me. Similarly, it's not autofocusing the search field.

Last, `onEmojiSelect` works, but in Safari, if I filter via the search input first, then _click_ to select an emoji, it doesn't fire the callback. If I filter via the search input and press `Enter`, it fires the callback as expected.

I don't know if this is an issue w/using it in React or... what. 

This issue a bit of a grab bag, so apologies for that. I'm happy to separate these into two issues if that's helpful.

**Comment by EtienneLem** [comment]
React issues have been addressed in **v5.2.0**. You can use [`@emoji-mart/react`](https://github.com/missive/emoji-mart#react) now.

**Comment by Boniqx** [comment]
It is still not working for react. and @emoji-mart/react also does not work. and is not on ts
